CREATE TABLE Users(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(200) UNIQUE,
	password TEXT
);

CREATE TABLE Task_types(
	ttid INT PRIMARY KEY AUTO_INCREMENT,
	uid INT,
	name TEXT,
	FOREIGN KEY (uid) REFERENCES Users(uid) ON DELETE CASCADE 
);

CREATE TABLE Tasks(
    tid INT PRIMARY KEY AUTO_INCREMENT,
 	uid INT,
	task_name TEXT,
	task_type INT,
	status INT,
	start DATETIME,
	end DATETIME,
	FOREIGN KEY (uid) REFERENCES Users(uid) ON DELETE CASCADE,
	FOREIGN KEY (task_type) REFERENCES Task_types(ttid) ON DELETE CASCADE
);

commit;